name       : haskell-pango
version    : 0.13.5.0
release    : 4
source     :
    - https://hackage.haskell.org/package/pango-0.13.5.0/pango-0.13.5.0.tar.gz : bf59b9273134e5d1c9c648a253e5a766cd1ef51afc2216175bce21a15b6d49e8
license    : LGPL-2.1
component  : programming.haskell
summary    : This package provides a wrapper around the Pango C library that allows
    high-quality rendering of Unicode text. It can be used either with Cairo to output
    text in PDF, PS or other documents or with Gtk+ to display text on-screen.
description: |
    This package provides a wrapper around the Pango C library that allows high-quality rendering of Unicode text. It can be used either with Cairo to output text in PDF, PS or other documents or with Gtk+ to display text on-screen.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pango)
    - ghc-devel
    - gtk2hs-buildtools-devel
    - haskell-cabal-install
    - haskell-cairo
    - haskell-glib
    - haskell-hashable-devel
    - haskell-hashtables-devel
    - haskell-primitive-devel
    - haskell-random-devel
    - haskell-text-devel
    - haskell-vector-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
